name: Run License Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  license_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@dev
    with:
      install_extras: '[audio-backend,mark1,stt,tts,skills,gui,bus,PHAL,all]'
      system_deps: 'swig libfann-dev portaudio19-dev libpulse-dev'
      exclude_packages: '^(ovos-audio-transformer-plugin-ggwave).*'
